# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qPnKn7I1xu9niR3xUh8PA8K6JTi-v9sX
"""

!unzip task.zip

import pixellib
from pixellib.custom_train import instance_custom_training

vis_img = instance_custom_training()
vis_img.load_dataset("task")
vis_img.visualize_sample()

import pixellib
from pixellib.custom_train import instance_custom_training

train_maskrcnn = instance_custom_training()
train_maskrcnn.modelConfig(network_backbone = "resnet50", num_classes= 2, batch_size = 6)
from google.colab import drive
drive.mount('/content/gdrive')
data = '/content/gdrive/My Drive/Colab Notebooks/mask_rcnn_coco.h5'
train_maskrcnn.load_pretrained_model(data)
train_maskrcnn.load_dataset("task")
train_maskrcnn.train_model(num_epochs = 1, augmentation=True, path_trained_models = "mask_rcnn_models")

import pixellib
from pixellib.instance import custom_segmentation

segment_image = custom_segmentation()
segment_image.inferConfig(num_classes= 2, class_names= ["laptop", "st"])
segment_image.load_model("mask_rcnn_models/mask_rcnn_model.001-1.819803.h5")
segment_image.segmentImage("1.jpg", show_bboxes=True, output_image_name="sample_out.jpg")

import pixellib
from pixellib.instance import custom_segmentation

test_video = custom_segmentation()
test_video.inferConfig(num_classes=  2, class_names=["laptop", "st"])
test_video.load_model("mask_rcnn_models/mask_rcnn_model.001-1.819803.h5")
test_video.process_video("svideo.mp4", show_bboxes = True,  output_video_name="video_out.mp4", frames_per_second=15)